app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
)   

from tracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('tracker.urls', namespace='tracker')),
]

app/tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.home, name='home'),
    path('trackers/', views.TrackerList.as_view(), name='list_trackers'),
    path('create/', views.TrackerCreateView.as_view(), name='create_tracker'),
    path('update/<int:pk>/', views.TrackerUpdateView.as_view(), name='update_tracker'),
    path('delete_creature/<int:pk>/', views.delete_creature, name='delete_creature'),
    path('run/<int:pk>/', views.RunView.as_view(), name='run')
]

app/tracker/models.py
from django.db import models
from django.contrib.auth.models import User


class Creature(models.Model):
    name = models.CharField(
        max_length=100,
    )
    initiative = models.CharField(
        max_length=5
    )
    tracker = models.ForeignKey(
        'Tracker',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'{self.name} {self.initiative}'


class Tracker(models.Model):
    name = models.CharField(
        max_length=20
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return f'{self.name}'

app/tracker/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

from . import models


User = get_user_model()

class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

class TrackerForm(forms.ModelForm):

    class Meta:
        model = models.Tracker
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class CreatureForm(forms.ModelForm):

    class Meta:
        model = models.Creature
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'initiative': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


CreatureFormSet = forms.inlineformset_factory(
    models.Tracker, models.Creature, form=CreatureForm,
    extra=1, can_delete=False
)

app/tracker/views.py
import random

from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import mixins
from django.views import generic
from django.contrib import messages

from . import models, forms

def home(request):
    return render(request, 'home.html')


class SignUpView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = forms.UserCreationForm

    def get_success_url(self):
        return reverse("login")


class TrackerInline(mixins.LoginRequiredMixin):
    form_class = forms.TrackerForm
    model = models.Tracker
    template_name = "tracker_create_or_update.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))
        
        self.object = form.save()

        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        

        return redirect("tracker:list_trackers") 
    
    def formset_creatures_valid(self, formset):
        creatures = formset.save(commit=False)
        for creature in creatures:
            creature.tracker = self.object
            creature.save()


class TrackerCreateView(TrackerInline, generic.CreateView):

    def get_context_data(self, **kwargs):
        context = super(TrackerCreateView, self).get_context_data(**kwargs)
        context['named_formsets'] = self.get_named_formsets()
        return context
    
    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'creatures': forms.CreatureFormSet(prefix='creatures'),
            }
        else:
            return {
                'creatures': forms.CreatureFormSet(self.request.POST or None, self.request.FILES or None,
                                                   prefix='creatures'),
            }
        

class TrackerUpdateView(TrackerInline, generic.UpdateView):

    def get_context_data(self, **kwargs):
        context = super(TrackerUpdateView, self).get_context_data(**kwargs)
        context['named_formsets'] = self.get_named_formsets()
        return context
    
    def get_named_formsets(self):
        return {
            'creatures': forms.CreatureFormSet(self.request.POST or None, self.request.FILES or None,
                                                instance=self.object,
                                                prefix='creatures')
        }
    

class TrackerList(mixins.LoginRequiredMixin, generic.ListView):
    model = models.Tracker
    template_name = 'tracker_list.html'
    context_object_name = 'trackers'

    def get_queryset(self):
        return models.Tracker.objects.filter(user=self.request.user)


def delete_creature(request, pk):
    try:
        creature = models.Creature.objects.get(id=pk)
    except models.Creature.DoesNotExist:
        messages.success(
            request, 'Object does not exist'
        )
        return redirect('tracker:update_tracker', pk=creature.tracker.id)
    
    creature.delete()
    messages.success(
        request, 'Object deleted'
    )
    return redirect('tracker:update_tracker', pk=creature.tracker.id)


class RunView(mixins.LoginRequiredMixin, generic.DetailView):
    template_name = 'run.html'
    context_object_name = 'tracker'

    def get_context_data(self, **kwargs):
        context = super(RunView, self).get_context_data(**kwargs)
        tracker = models.Tracker.objects.get(pk=self.kwargs['pk'])
        initiative_tracker = {}
        for creature in tracker.creature_set.all():
            initiative_tracker.update({
                creature.name: int(creature.initiative) + random.randint(1, 20)
            })
        
        context.update({
                'tracker': {k: v for k, v in sorted(initiative_tracker.items(), key=lambda item: item[1])},
                'tracker_id': tracker.pk
            })
        return context
        

    def get_object(self):
        return models.Tracker.objects.get(pk=self.kwargs['pk'])

app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Initiative Tracker</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body class="text-bg-dark">
        <div class="wrapper">
            {% block content %}
            {% endblock content %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block content %}

<div>

    <header class="text-center text-bg-dark" style="padding-top: 30vh">
        <h1>Initiative Tracker</h1>
    </header>

    {% if not request.user.is_authenticated %}
    
    <div class="d-flex justify-content-center mt-5">
        <a href="{% url 'login' %}" class="btn btn-outline-success me-2" style="width: 15vw" role="button">
            Login
        </a>
        <a href="{% url 'signup' %}" class="btn btn-success" style="width: 15vw" role="button">
            Sign-up
        </a>
    </div>

    {% else %}

    <div class="d-flex justify-content-center mt-5">
        <div>
            <div class="py-1">
                <a href="{% url 'tracker:list_trackers' %}" class="btn btn-outline-success me-2" style="width: 15vw" role="button">
                    Start
                </a>
            </div>
            <form class="py-1" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button href="{% url 'logout' %}" class="btn btn-outline-danger me-2" style="width: 15vw" role="button">
                    Logout
                </button>
            </form>
        </div>
    </div>

    {%endif%}

</div>
{% endblock content %}

app/templates/run.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card" style="margin-top: 10vh;">
        <div class="card-head card-head-secondary text-center">
            <h4 class="card-title">
                Tracker
            </h4>
        </div>
        <table class="table card-header">
            <thead class="text-secondary">
                <th>Name</th>
                <th>Initiative</th>
            </thead>
            <tbody id="item-creatures">
                {% for key, value in tracker.items %} 
                <tr>
                    <td>{{key}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td>
                        <a href="{% url 'tracker:update_tracker' tracker_id %}" class="btn btn-outline-warning mx-3 add-creatures" type="button">Edit</a>
                    </td>
                    <td>
                        <a href="{% url 'tracker:run' tracker_id %}" class="btn btn-outline-success mx-3 add-creatures" type="button">Next</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

app/templates/tracker_create_or_update.html
{% extends "base.html" %}

{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="tracker_form">
    {% csrf_token %}
    <div class="card">
        <div class="card-head card-head-secondary">
            <h4 class="card-title">
                Add tracker
            </h4>
        </div>
        {% for field in form %}
            <div class="form-group card-body">
                <label>{{ field.label }}</label>
                {% if field.field.required %}
                    <span style="color: red;" class="required">*</span>
                {% endif %}

                {{ field }}
                {% if field.help_text %}
                  <small style="color: gray;">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p style="color: red;">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    {% with named_formsets.creatures as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="creatures-template">
            <tr id="creatures-__prefix__" class=hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}

                {% for fields in formset.empty_form.visible_fields %}
                    <td>
                        {{ fields }}
                    </td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">
                    Add Creatures
                </h4>
            </div>
            <table class="table card-header">
                <thead class="text-secondary">
                    <th>Name</th>
                    <th>Initiative</th>
                    <th>Delete?</th>
                </thead>
                <tbody id="item-creatures">
                    {% for formss in formset %}
                    {{ formss.management_form }}
                    <tr id="creatures-{{ forloop.counter0 }}" class= hide_all>
                        {{ formss.id }}
                        {% for field in formss.visible_fields %}
                            <td>
                                {{ field }}
                                {% for error in field.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                {% endfor %}
                            </td>
                        {% endfor %}
                        {% if formss.instance.pk %}
                            <td>
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{formss.instance.pk}}">
                                    Delete
                                </button>
                                <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">
                                                    Are You Sure You Want To Delete This?
                                                </h5>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'tracker:delete_creature' formss.instance.pk %}" type="button" class="btn btn-primary">
                                                    Yes, Delete
                                                </a>
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                                    Close
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-creature-button" class="btn btn-outline-success me-2 add-creatures">Add More</a>
        </div>
    {% endwith %}
    <div class="form-group d-flex justify-content-center mt-3">
        <button type="submit" class="btn btn-outline-success me-2" style="width: 20%;">Submit</button>
        <a href="{% url 'tracker:run' tracker.pk %}" class="btn btn-outline-success mx-3" style="width: 20%;" type="button">Run</a>
    </div>
</form>

<script
src="https://code.jquery.com/jquery-3.4.1.js"
integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
crossorigin="anonymous"></script>

<script>
$(document).ready(function(){
    $('.add-creatures').click(function(ev) {
        ev.preventDefault();
        var count = $('#item-creatures').children().length;
        var tmplMarkup = $('#creatures-template').html();
        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
        $('#item-creatures').append(compiledTmpl);

        $('#id_creatures-TOTAL_FORMS').attr('value', count+1);
    });
});
</script>

{% endblock content %}

app/templates/tracker_list.html
{% extends "base.html" %}

{% block content %}
<div class="card">
    <div class="card-header card-header-secondary">
        <h4 class="card-title">
            Trackers
        </h4>
        <a href="{% url 'tracker:create_tracker' %}" class="btn btn-outline-success me-2" style="width: 15vw" role="button">
            Add more trackers
        </a>
    </div>
    <ul>
        {% for tracker in trackers %}
            <li class="card-body">
                <label class="mx-3 h5">{{ tracker.name }}</label> | 
                <a href="{% url 'tracker:update_tracker' tracker.id %}" class="btn btn-outline-warning mx-3 add-creatures" type="button">Edit</a> |
                <a href="{% url 'tracker:run' tracker.pk %}" class="btn btn-outline-success mx-3 add-creatures" type="button">Run</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}